### ISSUE TITLE
[BUG] After upgrading to 4.4.3 some shortcuts stopped working

### ISSUE THREAD

**Issue by damusnet** [JohannesKlauss/react-hotkeys-hook#1110]
**Describe the bug**
`shit+?` and `shift+plus,shift+bracketright` used to work, now they don't

**To Reproduce**
1. Go to [CodeSandbox](https://codesandbox.io/p/devbox/long-violet-8xccvl?file=%2Fapp%2Fpage.tsx%3A8%2C1) repro
2. Make sure to open the console
3. Try hitting `shift+?`, `shift+plus`, `shift+minus` (with `+` and `-` keys respectively)
4. Only `shift+minus` will log to the console

**Expected behavior**
Existing shortcuts should still work

**Screenshots**
<img width="1840" alt="image" src="https://github.com/JohannesKlauss/react-hotkeys-hook/assets/433409/bcf9fe8f-4da3-4640-86c8-2e68f59239fb">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: Version 120.0.6099.129 (Official Build) (arm64)

**Comment by rawpixel-vincent** [comment]
same here, commenting out that line:
```
 // if (!(keys != null && keys.includes(keyCode)) && !['ctrl', 'control', 'unknown', 'meta', 'alt', 'shift', 'os'].includes(keyCode)) {
  //   console.log("elmoo");
  //   return false;
  // }
  ```
  in `isHotkeyMatchingKeyboardEvent()` 
  fix the issue, if that helps

happens is firefox / chrome - linux and macos

I've managed to log that before this condition execute, and I'm not sure why "right" is in keys, maybe some memoization issue 🤷🏻 
`{"pressedKey":"delete","keyCode":"","keys":["right"]}`

downgrading to 4.4.1 fixed the issue, all good 👍🏻

**Comment by JohannesKlauss** [comment]
Weirdly enough only `Shift+?` works for me, the other two don't register.

**Comment by JohannesKlauss** [comment]
Fixed in 4.4.4

**Comment by damusnet** [comment]
Thank you for looking into this.

After updating the CodeSandbox to `4.4.4`: `shift+?` and `shift+minus` now both work, but `shift+plus` still doesn't.

Note also that on a extended keyboard with separate numpad, neither `shift+plus` nor `shift+minus` work.
