### ISSUE TITLE
`ref` returned from `useHotkeys` does not work on conditionally rendered elements

### ISSUE THREAD

**Issue by chernetsov0** [JohannesKlauss/react-hotkeys-hook#1198]
**Is your feature request related to a problem? Please describe.**
It took me a lot of frustration to realize that using `ref` returned from `useHotkeys` on conditionally rendered element which is initially absent results in weird (and possibly unintended) behavior:

* On initial render `keydown` event listener will be added on the `document`.
* When the element becomes present `ref` will update.
* Listener will still be on the `document` but behave like it is added on the element.

As a result all `keydown` events will be `stopPropagation`ed and `preventDefault`ed when the focus is outside the element. Among other things, Tab navigation stops working, which is an accessibility concern.

**Describe the solution you'd like**
Some way to pass additional dependencies for `useLayoutEffect` inside the `useHotkeys` hook, e.g. through `options` object.

**Describe alternatives you've considered**
1. Passing dependencies for the `useCallback` to the `useLayoutEffect` as well.
2. Mentioning in the documentation, that `ref` from `useHotkeys` does not support conditionally rendered elements as it breaks accessibility and potentially other hotkeys. This can always be mitigated by wrapping conditionally rendered element in a component.

**Comment by AlexGalays** [comment]
yeah that ref in general doesn't work super well.

If you hit the shortcut from an unrelated element and shortly after do it again on the element with the ref, you can also get 2 function calls instead of one.

**Comment by WillGarman** [comment]
I ran into this as-well - was very annoying to figure out. But luckily I was able to just move the ref to the parent element, although some may be in a different position. That seemed to fix everything

The symptoms were that I had some other inputs on the page that I realized I couldn't type into on the initial render of the conditional element that had the ref attached to it. Clicking off the page after initial render and coming back fixed it. But made for a couple hour debugging session on what was wrong.

**Comment by zeorin** [comment]
Should be fixed by https://github.com/JohannesKlauss/react-hotkeys-hook/pull/1132

**Comment by JohannesKlauss** [comment]
Yes, this was released in 4.5.1 just now.

**Comment by AlexGalays** [comment]
FYI, we still have a super critical bug where the whole app is locked up (all keyboard events are prevented) when going from a div ref (that doesn't even cover the whole app) to a null ref (the new screen doesn't render that element anymore)

**Comment by oleksandr-danylchenko** [comment]
Thanks, @zeorin. The https://github.com/JohannesKlauss/react-hotkeys-hook/pull/1132 is an exact fix I'd like to see in the codebase of the current library. I faced the same blocked tab navigation in my app. It came from the fact that the listener was initially registered on a `document`, but the `ref.current` got populated later, causing an inadequate comparison for the following lines:
https://github.com/JohannesKlauss/react-hotkeys-hook/blob/f2006c7ba118175c7cd673c13296ebfb618bbd7a/packages/react-hotkeys-hook/src/lib/useHotkeys.ts#L79-L84

<img height="200" alt="Image" src="https://github.com/user-attachments/assets/b4fea78f-f875-40bf-aac2-995cb68dcf66" />

---

UPD: I reopened an issue in https://github.com/JohannesKlauss/react-hotkeys-hook/issues/1313
