### ISSUE TITLE
window is not defined (SSR)

### ISSUE THREAD

**Issue by nicksrandall** [JohannesKlauss/react-hotkeys-hook#827]
Would it be possible to make this hook SSR compatible by wrapping this fn in a guard to only run on the client?

https://github.com/JohannesKlauss/react-hotkeys-hook/blob/cc8aeed82c4bf1963afacc47efb59b2a5a8e077f/src/isHotkeyPressed.ts#L42

**Comment by JohannesKlauss** [comment]
Yes, I'll fix that later this day.

**Comment by JohannesKlauss** [comment]
Fixed in 4.0.3

**Comment by nicksrandall** [comment]
@JohannesKlauss I'm still getting an issue when running server-side because of the usage of `useLayoutEffect` which is not supported in a server environment. I've seen may other libraries get around this issue by creating an abstraction called `useSafeLayoutEffect` which will run a regular `useEffect` on server and `useLayoutEffect` on client. 

See: https://github.com/chakra-ui/chakra-ui/blob/260076e2ac6165c8079c800475b9d7a9ca0f29a2/packages/components/descendant/src/utils.ts#L53-L54

**Comment by JohannesKlauss** [comment]
This should be fixed with version 4.0.4
