### ISSUE TITLE
[BUG] "meta" key is not working after upgrading to version `4.3.5`

### ISSUE THREAD

**Issue by mforman1** [JohannesKlauss/react-hotkeys-hook#938]
**Describe the bug**
`meta` key is not working any more after upgrading from version `4.3.2` to version `4.3.5`

**To Reproduce**
1. Upgrade to version `4.3.5`

**Expected behavior**
`meta` key to work 

**Desktop (please complete the following information):**
 - Windows
 - Chrome

**Comment by mforman1** [comment]
I just checked and the first occurence of the issue is in version `4.3.3`

**Comment by Akrion** [comment]
I can confirm that as well. `meta` does not work properly in Windows/Chrome. Does work on OSX/Chrome however.

**Comment by JohannesKlauss** [comment]
I'll check it out. Probably should also run this lib against a e2e suite on different OS by now, just to increase the stability.

**Comment by JohannesKlauss** [comment]
I only have access to windows via Parallels Desktop and I'm not sure how great this is, because it also does mapping from my mac keyboard layout to the windows layout, but I think it is fixed.

Could you please install version `4.3.6-4` and check if the issue still persists?

**Comment by Akrion** [comment]
> 4.3.6-4

Tested on my end. Meta works as expected now in osX and it is "converted" to `Ctrl` on Chrome on Windows. Thank you!

**Comment by JohannesKlauss** [comment]
Awesome. I'll release a proper version tomorrow.

**Comment by JohannesKlauss** [comment]
Fixed in 4.3.6

**Comment by ctjhoa** [comment]
@JohannesKlauss 
Hi,
Sorry but I still have issue with the meta key in `4.3.7`.
Here is an example of `useHotkeys('meta+k'` with an event `ctrl+k` on chromium linux.

![2023-02-27-112400_2256x974_scrot](https://user-images.githubusercontent.com/1716173/221538419-e507a1f6-0d80-4eee-8c3d-31a5a0954c00.png)

**Comment by mforman1** [comment]
Same for me

**Comment by joaom00** [comment]
The docs say:

> The meta key is the same as cmd on macOS and ctrl on Windows/Linux.

Is it handled by the lib? because I tested it in 4 browsers on windows (chrome, firefox, edge, brave) and none of them treats the control key as meta key, the meta key on windows is the `Windows` key, apart from firefox which no longer treats the `Windows` key as meta key

**Comment by JohannesKlauss** [comment]
> @JohannesKlauss Hi, Sorry but I still have issue with the meta key in `4.3.7`. Here is an example of `useHotkeys('meta+k'` with an event `ctrl+k` on chromium linux.
> 
> ![2023-02-27-112400_2256x974_scrot](https://user-images.githubusercontent.com/1716173/221538419-e507a1f6-0d80-4eee-8c3d-31a5a0954c00.png)

Are you sure that the event is `ctrl+k`? What does the console output say for this [https://codesandbox.io/s/react-hotkeys-template-bzvk53?file=/src/App.js](Codesandbox)?

**Comment by ctjhoa** [comment]
![2023-03-03-154257_1807x1211_scrot](https://user-images.githubusercontent.com/1716173/222749477-0adc9b2e-52f7-4f6d-a505-16909ec8dd77.png)
@JohannesKlauss Yes I'm sure about the `ctrl+k`. You can see in my screenshot that the `ctrlKey` boolean is true.

**Comment by JohannesKlauss** [comment]
But do you want to isten to ctrl+k or to meta+k? I am bit confused about the actual problem.

**Comment by ctjhoa** [comment]
> But do you want to isten to ctrl+k or to meta+k? I am bit confused about the actual problem.

As the doc says

> The meta key is the same as cmd on macOS and ctrl on Windows/Linux.

So I expect that the listener `meta+k` should be triggered by `ctrl+k` on Linux.
If the doc is wrong, you can ignore my issue but doc should be fixed.

**Comment by JohannesKlauss** [comment]
Ah gotcha! Thanks for the clarification :) I am updating the docs accordingly

**Comment by WesleyYue** [comment]
@JohannesKlauss I'm new to the library but I found the area around the definition of `meta` a bit confusing. There's a lot of places in the docs that imply meta = cmd on macos/ctrl on windows.

- https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/basic-usage#keystrokes (the parts about meta + t on chrome)
- https://react-hotkeys-hook.vercel.app/docs/documentation/useHotkeys/disable-hotkeys#prevent-default-browser-behavior

I personally expected `meta` to map to cmd (macOS) / ctrl (windows), which is usually the behaviour in the context of shortcuts (see VSCode shortcut configs for example). I can see the argument for `meta` being the `os` key on windows in other contexts, but I'd think most people here are trying to build a suite of keys like (`meta+z`, `meta+s`, etc).

Is there a simple way to achieve the `meta` = `ctrl`(windows) / `cmd` (macOS) with this library? It would be great to avoid writing OS detection everywhere.

**Comment by WesleyYue** [comment]
Ah, it looks like `mod` is what I'm looking for.
